server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Enrutar errores a la página 404 generada por Hugo
    error_page 404 /404.html;

    # 2. Activar compresión GZIP (Acelera la carga de la web)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # 3. Caché agresivo para imágenes y estilos (FinOps y Performance)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|pdf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # 4. Cabeceras de Seguridad DevSecOps
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ =404;
    }
}